const $ = (s, root=document) => root.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now = new Date();
const iso = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today = iso(now);
const dateAt = (offset=0) => {const d=new Date(now);d.setDate(d.getDate()+offset);return iso(d)};
const uid = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const money = n => Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
let app='ledger', mode='own', view='all', filter='all', query='', selectedNote=null;
let month=new Date(now.getFullYear(),now.getMonth(),1), selectedDate=today;
let memory={}, storageOK=true;
const names={ledger:['拾账','MONEY, MADE CLEAR','日常账本'],notes:['一页','ROOM FOR THOUGHT','我的记事本'],calendar:['朝夕','MAKE ROOM FOR LIFE','我的日历']};
function key(){return `tiana-everyday-prototype-v1-${app}-${mode}`}
function read(){try{return JSON.parse(localStorage.getItem(key())||'null')||memory[key()]||[]}catch{return memory[key()]||[]}}
function write(data){memory[key()]=data;try{localStorage.setItem(key(),JSON.stringify(data))}catch{storageOK=false;toast('浏览器存储不可用，本次内容仅保留到关闭页面。')}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function seed(){if(read().length)return;const samples={ledger:[{id:uid(),title:'午后的咖啡',amount:28,type:'expense',category:'餐饮',date:today,note:'给忙碌的一天留一点空隙'},{id:uid(),title:'地铁通勤',amount:6,type:'expense',category:'交通',date:today,note:''},{id:uid(),title:'一周食材',amount:186.5,type:'expense',category:'购物',date:dateAt(-1),note:'水果、蔬菜和早餐'},{id:uid(),title:'九月读书计划',amount:68,type:'expense',category:'生活',date:dateAt(-2),note:''},{id:uid(),title:'项目收入',amount:3200,type:'income',category:'收入',date:dateAt(-3),note:'设计项目尾款'}],notes:[{id:uid(),title:'把周末留给自己',body:'这周想慢一点。\n\n去逛一直想去的花市，买一束洋桔梗。\n找一家窗边有阳光的小店，读完那本书。\n\n想做的三件小事\n☐ 整理书架，留下真正喜欢的书\n☐ 试着做一次番茄炖牛腩\n☐ 傍晚沿着河边走一走\n\n不需要安排得满满当当，留一点空白也很好。',folder:'生活',pinned:true,updated:Date.now()},{id:uid(),title:'产品讨论 · 灵感收集',body:'今天讨论了什么\n让第一次打开应用的人，更容易开始。\n\n下一步\n把复杂的设置收起来，先完成一个小动作。',folder:'工作',pinned:false,updated:Date.now()-3600000},{id:uid(),title:'最近读到的一句话',body:'生活的细节里，总藏着一些值得记录的东西。\n\n留意今天的光线、路边的树和偶然听见的故事。',folder:'灵感',pinned:false,updated:Date.now()-86400000}],calendar:[{id:uid(),title:'产品灵感碰头会',date:today,start:'10:00',end:'11:00',category:'工作',location:'线上会议',note:'带上本周收集的三个想法'},{id:uid(),title:'给自己留一点阅读时间',date:today,start:'20:00',end:'20:45',category:'生活',location:'家',note:'读完书签后的二十页'},{id:uid(),title:'和朋友吃顿饭',date:dateAt(2),start:'18:30',end:'20:00',category:'生活',location:'街角小馆',note:''},{id:uid(),title:'一周回顾',date:dateAt(4),start:'16:00',end:'16:30',category:'个人',location:'',note:''},{id:uid(),title:'去公园走走',date:dateAt(-2),start:'17:00',end:'18:00',category:'生活',location:'河边公园',note:''}]};write(samples[app])}
function navButton(id,icon,title){return `<button data-view="${id}" class="${view===id?'selected':''}"><span class="nav-icon" aria-hidden="true">${icon}</span>${title}</button>`}
function shell(content){const [name,en,space]=names[app];let nav=app==='ledger'?navButton('all','▤','收支明细')+navButton('analysis','◷','分类统计'):app==='notes'?navButton('all','▤','全部笔记')+navButton('pinned','⌑','置顶笔记')+['生活','工作','灵感'].map(n=>navButton(n,'▱',n)).join(''):navButton('all','▦','月历')+navButton('agenda','☷','日程列表');return `<div class="shell ${app}"><aside class="sidebar"><div class="brand"><span class="brandmark" aria-hidden="true">${app==='ledger'?'拾':app==='notes'?'页':'朝'}</span><div>${name}<small>${en}</small></div></div><nav class="side-nav" aria-label="应用导航">${nav}</nav><div class="side-bottom"><div class="side-note">${app==='ledger'?'每一笔，都让生活更清楚。':app==='notes'?'给想到的事，留一页空间。':'把重要的事，放进日子里。'}</div><div class="profile"><span class="avatar">我</span><span>${space}<br><small>${mode==='demo'?'示例体验空间':'个人空间'}</small></span></div></div></aside><main class="main">${content}</main></div>`}
function render(){closeDropdown();document.documentElement.style.setProperty('--accent',app==='notes'?'#7457a1':app==='calendar'?'#c56340':'#315fda');document.documentElement.style.setProperty('--soft',app==='notes'?'#f1ecf8':app==='calendar'?'#faeee8':'#eaf0ff');document.title=`${names[app][0]} · 交互原型`;$('.reviewbar nav').querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.hash===`#${app}`));$('#mode-label').textContent=mode==='demo'?'示例空间 · 仅浏览器保存':'我的空间 · 仅浏览器保存';$('#toggle-mode').textContent=mode==='demo'?'开始自己的记录':'体验示例';$('#app').innerHTML=shell(app==='ledger'?ledger():app==='notes'?notes():calendar());bind();}
function monthControl(){return `<div class="month-nav"><button data-month="-1" aria-label="上个月">‹</button><strong>${month.getFullYear()} 年 ${month.getMonth()+1} 月</strong><button data-month="1" aria-label="下个月">›</button></div>`}
function monthEntries(){const prefix=iso(month).slice(0,7);return read().filter(e=>e.date.startsWith(prefix))}
function ledger(){let entries=monthEntries(),expense=entries.filter(e=>e.type==='expense').reduce((n,e)=>n+Math.round(e.amount*100),0)/100,income=entries.filter(e=>e.type==='income').reduce((n,e)=>n+Math.round(e.amount*100),0)/100;
const categories=['餐饮','交通','购物','生活','其他'];const sums=categories.map(c=>[c,entries.filter(e=>e.type==='expense'&&e.category===c).reduce((n,e)=>n+Math.round(e.amount*100),0)/100]).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);
const chart=sums.length?sums.map(([c,n])=>`<div class="bar-row"><div class="bar-meta"><span>${c}</span><span>¥ ${money(n)} · ${Math.round(n/expense*100)}%</span></div><div class="track"><i style="width:${n/expense*100}%"></i></div></div>`).join(''):'<div class="empty-hint">记下第一笔支出后，这里会告诉你钱花在了哪里。</div>';
let rows=entries.filter(e=>filter==='all'||e.type===filter).sort((a,b)=>b.date.localeCompare(a.date));return `<header class="topline"><div><p class="eyebrow">把生活，记清楚</p><h1>${view==='analysis'?'每一笔的去向':'我的日常账本'}</h1><p class="subtitle">从一杯咖啡开始，慢慢了解自己的生活。</p></div><button class="primary" data-add-ledger>＋ 记一笔</button></header><div class="ledger-layout"><section><div class="panel balance"><div><small>本月支出</small><div class="big"><span>¥</span>${money(expense)}</div>${monthControl()}</div><div class="balance-right"><div class="stat-row"><span>本月收入</span><strong class="green">+ ${money(income)}</strong></div><div class="stat-row"><span>本月结余</span><strong>${money(income-expense)}</strong></div></div></div>${view==='analysis'?`<div class="panel"><div class="panel-heading"><h2>支出构成</h2><small>${entries.filter(e=>e.type==='expense').length} 笔支出</small></div>${chart}<p class="summary-foot">按所选月份的实际支出计算，收入不计入支出占比。</p></div>`:`<div class="panel"><div class="panel-heading"><h2>收支明细</h2><div class="filters" aria-label="收支筛选">${[['all','全部'],['expense','支出'],['income','收入']].map(([k,t])=>`<button data-filter="${k}" class="${filter===k?'selected':''}">${t}</button>`).join('')}</div></div>${rows.length?`<table class="ledger-table"><thead><tr><th>账单</th><th class="category-column">分类</th><th style="text-align:right">金额</th><th><span class="muted">操作</span></th></tr></thead><tbody>${rows.map(e=>`<tr><td><div class="entry-title"><span class="category-icon">${e.type==='income'?'↙':({'餐饮':'◒','交通':'↗','购物':'▱','生活':'⌂'}[e.category]||'◇')}</span><div>${esc(e.title)}<small>${esc(e.date)}</small></div></div></td><td class="category-column muted">${esc(e.category)}</td><td class="amount ${e.type==='income'?'green':''}">${e.type==='income'?'+':'−'} ${money(e.amount)}</td><td><button class="edit-link" data-edit-ledger="${e.id}" aria-label="编辑${esc(e.title)}">编辑</button></td></tr>`).join('')}</tbody></table>`:`<div class="welcome"><div class="welcome-symbol">＋</div><h2>${entries.length?'没有这类账单':'今天的第一笔，从这里开始'}</h2><p>${entries.length?'试试其他筛选，或添加一笔新的记录。':'不用先建账户或设置预算。选一个分类，记下金额，就开始了。'}</p><button class="primary" data-add-ledger>记下第一笔</button></div>`}</div>`}</section><aside class="aside-stack"><section class="panel"><div class="panel-heading"><h3>从一笔小事开始</h3><small>快速记账</small></div><div class="quick-buttons">${[['餐饮','一杯咖啡'],['交通','一段通勤'],['购物','买点喜欢的'],['收入','一份收获']].map(([c,t])=>`<button data-quick-ledger="${c}"><b>${c}</b><small>${t}</small></button>`).join('')}</div><p class="micro">分类已选好，填个金额就能记。</p></section><section class="panel"><h3>钱花在了哪里</h3>${chart}</section><p class="micro" style="padding:0 8px">每一笔小记录，都是更了解自己的开始。</p></aside></div>`}
function showModal(html){closeDropdown();$('#modal').innerHTML=html;$('#modal').showModal();$('[data-close]',$('#modal'))?.addEventListener('click',()=>$('#modal').close())}
function ledgerForm(id,category='餐饮'){const existing=read().find(e=>e.id===id),e=existing||{title:'',amount:'',type:category==='收入'?'income':'expense',category,date:today,note:''};showModal(`<form id="entry-form"><div class="dialog-top"><div><h2>${existing?'编辑账单':'记下这一笔'}</h2><small>不用复杂，记清楚就好。</small></div><button type="button" data-close aria-label="关闭">✕</button></div><div class="form-grid"><div class="field"><span>类型</span>${dropdown('type','类型',e.type,[['expense','支出'],['income','收入']])}</div><label>金额（元）<input name="amount" type="number" min="0.01" step="0.01" required value="${e.amount}" placeholder="0.00" autofocus></label><label class="full">这笔是什么<input name="title" value="${esc(e.title)}" placeholder="例如：午后的咖啡（可不填）"></label><div class="field"><span>分类</span>${dropdown('category','分类',e.category,e.type==='income'?['收入']:['餐饮','交通','购物','生活','其他'])}</div><label>日期<input name="date" type="date" value="${e.date}" required></label><label class="full">备注<input name="note" value="${esc(e.note)}" placeholder="再记一点细节（可不填）"></label></div><div class="dialog-actions">${existing?'<button type="button" class="danger" id="delete-entry">删除账单</button>':''}<div class="inline"><button type="button" onclick="document.querySelector('dialog').close()">取消</button><button class="primary" type="submit">保存账单</button></div></div></form>`);$('[name=type]').onchange=e=>{const categories=e.target.value==='income'?['收入']:['餐饮','交通','购物','生活','其他'];$('[name=category]').closest('.dropdown').outerHTML=dropdown('category','分类',categories[0],categories)};$('#entry-form').onsubmit=event=>{event.preventDefault();let f=Object.fromEntries(new FormData(event.target));f={...f,id:id||uid(),amount:Math.round(Number(f.amount)*100)/100,title:f.title.trim()||f.category};write(existing?read().map(item=>item.id===id?f:item):[f,...read()]);month=new Date(`${f.date}T12:00:00`);month.setDate(1);$('#modal').close();render();toast('账单已保存')};$('#delete-entry')?.addEventListener('click',()=>confirmDelete('删除这笔账单？',()=>{write(read().filter(e=>e.id!==id));render();toast('账单已删除')}))}
const templates={blank:{title:'',body:'',folder:'生活'},daily:{title:'今天，想记下这些',body:'今天的一件小事\n\n\n此刻的心情\n\n\n想留给明天的话\n',folder:'生活'},meeting:{title:'会议记录',body:'讨论主题\n\n\n关键结论\n\n\n接下来要做的事\n☐ \n',folder:'工作'},idea:{title:'一个新想法',body:'突然想到\n\n\n为什么值得试试\n\n\n可以迈出的第一步\n',folder:'灵感'}};
function noteItems(){return read().filter(n=>(view==='all'||(view==='pinned'?n.pinned:n.folder===view))&&(`${n.title} ${n.body}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updated-a.updated)}
function noteCards(){return noteItems().map(n=>`<button class="note-card ${n.id===selectedNote?'selected':''}" data-note="${n.id}"><strong>${n.pinned?'⌑ ':''}${esc(n.title||'无标题笔记')}</strong><p>${esc(n.body||'还没有写下内容')}</p><small>${esc(n.folder)} · ${new Date(n.updated).toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</small></button>`).join('')||`<div class="empty-hint">${query?'没有找到匹配的笔记。':view==='pinned'?'把常用的笔记置顶，就能在这里快速找到。':'这里等着你的第一篇笔记。'}</div>`}
function notes(){let n=read().find(n=>n.id===selectedNote);return `<header class="notes-top"><div><p class="eyebrow">思绪有地方落下</p><h1>${view==='all'?'全部笔记':view==='pinned'?'置顶笔记':esc(view)}</h1></div><div class="inline"><input id="note-search" type="search" aria-label="搜索笔记" placeholder="搜索标题或内容" value="${esc(query)}"><button class="primary" data-template="blank">＋ 新建</button></div></header><div class="notes-workspace ${n?'has-note':''}"><section class="note-list"><div class="note-list-head"><span id="note-count">${noteItems().length} 篇笔记</span><span>置顶优先 · 最近编辑</span></div><div id="note-cards">${noteCards()}</div></section><section class="editor ${n?'has-content':''}">${n?`<div class="editor-toolbar"><div class="inline"><button class="mobile-back" id="notes-back">‹ 列表</button><span id="save-state">${storageOK?'已保存到当前原型':'仅保存在本次页面'}</span></div><div><button id="pin-note">${n.pinned?'取消置顶':'置顶'}</button><button class="danger" id="delete-note">删除</button></div></div><input class="editor-title" id="note-title" value="${esc(n.title)}" placeholder="给这一页起个名字" aria-label="笔记标题"><div class="editor-meta"><div class="inline"><span>收纳到</span>${dropdown('folder','收纳到',n.folder,['生活','工作','灵感'],'note-folder',true)}</div><span id="word-count">${n.body.length} 字 · 输入后自动保存</span></div><textarea id="note-body" class="editor-body" placeholder="从想到的第一句话开始……" aria-label="笔记内容">${esc(n.body)}</textarea>`:`<div class="welcome"><div class="welcome-symbol">页</div><h2>${read().length?'打开一页，继续写':'第一篇，不用想好才开始'}</h2><p>记一个念头，留一份会议记录，或者只是写下今天。</p><div class="template-list">${[['blank','＋','空白一页','没有格式，想到什么就写什么'],['daily','☀','随手记','从今天的一件小事开始'],['meeting','▤','会议记录','主题、结论与下一步'],['idea','◇','灵感便笺','把一闪而过的念头留住']].map(([k,i,t,s])=>`<button data-template="${k}"><span class="template-number">${i}</span><span><b>${t}</b><small>${s}</small></span><span style="margin-left:auto">↗</span></button>`).join('')}</div><p class="micro">选择后生成可编辑草稿，写下的内容会自动保存。</p></div>`}</section></div>`}
function createNote(t){const n={...templates[t],id:uid(),pinned:false,updated:Date.now()};if(['生活','工作','灵感'].includes(view))n.folder=view;write([n,...read()]);selectedNote=n.id;view='all';query='';render();$('#note-title').focus()}
function saveNote(){const data=read(),n=data.find(n=>n.id===selectedNote);if(!n)return;n.title=$('#note-title').value;n.body=$('#note-body').value;n.folder=$('#note-folder').value;n.updated=Date.now();write(data);$('#save-state').textContent=storageOK?'已保存到当前原型':'仅保存在本次页面';$('#word-count').textContent=`${n.body.length} 字 · 输入后自动保存`;$('#note-cards').innerHTML=noteCards();$('#note-count').textContent=`${noteItems().length} 篇笔记`}
function eventItems(date){return read().filter(e=>e.date===date).sort((a,b)=>a.start.localeCompare(b.start))}
function agendaRow(e){return `<button class="agenda-item" data-event="${e.id}"><small>${e.start} — ${e.end} · ${esc(e.category)}</small><strong>${esc(e.title)}</strong><small>${esc(e.location||'未设置地点')}</small></button>`}
function calendar(){let year=month.getFullYear(),m=month.getMonth(),start=new Date(year,m,1),offset=(start.getDay()+6)%7,total=new Date(year,m+1,0).getDate(),cells=Math.ceil((total+offset)/7)*7;let selected=new Date(`${selectedDate}T12:00:00`),events=eventItems(selectedDate);return `<header class="topline"><div><p class="eyebrow">留出时间，好好生活</p><h1>让日子有点期待</h1><p class="subtitle">工作、生活，还有留给自己的时间。</p></div><button class="primary" data-new-event>＋ 新建日程</button></header>${read().length?'':`<div class="start-strip"><div><strong>从一个确定的小计划开始</strong><p>点一下日期，安排散步、阅读，或下一次见面。</p></div><button data-event-template="阅读时间">安排阅读时间 ↗</button></div>`}<div class="calendar-layout"><section class="calendar-board"><header class="calendar-head"><h2>${year} 年 ${m+1} 月</h2><div class="month-nav"><button data-month="-1" aria-label="上个月">‹</button><button id="today">今天</button><button data-month="1" aria-label="下个月">›</button></div></header>${view==='agenda'?`<div style="padding:0 24px 24px">${monthEntries().sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)).map(e=>`<div><p class="micro">${e.date}</p>${agendaRow(e)}</div>`).join('')||'<div class="welcome"><h2>这个月，还留着很多可能</h2><p>新建一个日程，为重要的事情留出时间。</p><button class="primary" data-new-event>添加第一个日程</button></div>'}</div>`:`<div class="weekdays">${['一','二','三','四','五','六','日'].map(d=>`<span>周${d}</span>`).join('')}</div><div class="month-grid">${Array.from({length:cells},(_,i)=>{let d=new Date(year,m,i-offset+1),date=iso(d),items=eventItems(date);return `<button class="day ${d.getMonth()!==m?'outside':''} ${date===today?'today':''} ${date===selectedDate?'chosen':''}" data-date="${date}" aria-label="${date}，${items.length}个日程"><span class="day-number">${d.getDate()}</span>${items.slice(0,2).map(e=>`<span class="event-chip ${e.category==='工作'?'work':e.category==='生活'?'life':''}">${e.start} ${esc(e.title)}</span>`).join('')}${items.length>2?`<small>另 ${items.length-2} 项</small>`:''}</button>`}).join('')}</div>`}</section><aside class="aside-stack"><section class="panel"><small>${selected.toLocaleDateString('zh-CN',{month:'long',weekday:'long'})}</small><div class="agenda-date">${selected.getDate()}<span style="font-size:14px;letter-spacing:0;color:var(--muted);margin-left:10px">${selectedDate===today?'今天':''}</span></div><div class="panel-heading" style="margin:20px 0 0"><h3>这一天的安排</h3><small>${events.length} 项</small></div>${events.map(agendaRow).join('')||'<p class="day-empty">还没有安排。<br>留白很好，也可以放进一件期待的事。</p>'}<button class="secondary" data-new-event style="width:100%;margin-top:20px;color:var(--accent)">＋ 添加日程</button></section><section class="panel"><h3>给生活一点位置</h3><p class="micro">一个小计划，也值得被认真安排。</p><div class="template-tags">${['阅读时间','出门散步','朋友聚餐'].map(t=>`<button data-event-template="${t}">${t} ＋</button>`).join('')}</div></section></aside></div>`}
function eventForm(id,title=''){const existing=read().find(e=>e.id===id),e=existing||{title,date:selectedDate,start:'19:00',end:'20:00',category:'生活',location:'',note:''};showModal(`<form id="event-form"><div class="dialog-top"><div><h2>${existing?'编辑日程':'留出一段时间'}</h2><small>为重要的小事，留一个位置。</small></div><button type="button" data-close aria-label="关闭">✕</button></div><div class="form-grid"><label class="full">日程名称<input name="title" value="${esc(e.title)}" required placeholder="准备做点什么？" autofocus></label><label>日期<input name="date" type="date" value="${e.date}" required></label><div class="field"><span>分类</span>${dropdown('category','分类',e.category,['工作','生活','个人'])}</div><label>开始时间<input name="start" type="time" value="${e.start}" required></label><label>结束时间<input name="end" type="time" value="${e.end}" required></label><label class="full">地点<input name="location" value="${esc(e.location)}" placeholder="在家、线上，或某个地方（可不填）"></label><label class="full">备注<textarea name="note" placeholder="想提前记住的事（可不填）">${esc(e.note)}</textarea></label></div><p class="micro">当前原型支持单日定时日程，不发送提醒。</p><div class="dialog-actions">${existing?'<button type="button" class="danger" id="delete-event">删除日程</button>':''}<div class="inline"><button type="button" onclick="document.querySelector('dialog').close()">取消</button><button class="primary" type="submit">保存日程</button></div></div></form>`);$('#event-form').oninput=()=>{$('[name=end]').setCustomValidity('')};$('#event-form').onsubmit=event=>{event.preventDefault();const f=Object.fromEntries(new FormData(event.target));if(f.end<=f.start){$('[name=end]').setCustomValidity('结束时间需要晚于开始时间');$('[name=end]').reportValidity();return}f.id=id||uid();write(existing?read().map(item=>item.id===id?f:item):[...read(),f]);selectedDate=f.date;month=new Date(`${f.date}T12:00:00`);month.setDate(1);$('#modal').close();render();toast('日程已保存')};$('#delete-event')?.addEventListener('click',()=>confirmDelete('删除这个日程？',()=>{write(read().filter(e=>e.id!==id));render();toast('日程已删除')}))}
function confirmDelete(title,action){$('#modal').close();showModal(`<div class="dialog-top"><h2>${title}</h2><button data-close aria-label="关闭">✕</button></div><p class="subtitle">只影响当前原型空间的这条记录。</p><div class="dialog-actions"><button id="confirm-cancel">取消</button><button class="primary" id="confirm-delete">确认删除</button></div>`);$('#confirm-cancel').onclick=()=>$('#modal').close();$('#confirm-delete').onclick=()=>{$('#modal').close();action()}}
function bind(){document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+Number(b.dataset.month),1);render()});$('#note-search')?.addEventListener('input',e=>{query=e.target.value;if(matchMedia('(max-width:700px)').matches){selectedNote=null;$('.notes-workspace').classList.remove('has-note')}$('#note-cards').innerHTML=noteCards();$('#note-count').textContent=`${noteItems().length} 篇笔记`});for(const id of ['note-title','note-body','note-folder'])$('#'+id)?.addEventListener('input',saveNote);$('#pin-note')?.addEventListener('click',()=>{write(read().map(n=>n.id===selectedNote?{...n,pinned:!n.pinned}:n));render()});$('#delete-note')?.addEventListener('click',()=>confirmDelete('删除这篇笔记？',()=>{write(read().filter(n=>n.id!==selectedNote));selectedNote=null;render();toast('笔记已删除')}));$('#notes-back')?.addEventListener('click',()=>{selectedNote=null;render()});$('#today')?.addEventListener('click',()=>{month=new Date(now.getFullYear(),now.getMonth(),1);selectedDate=today;render()})}
$('#app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if('view'in d){view=d.view;selectedNote=null;render()}else if('filter'in d){filter=d.filter;render()}else if('addLedger'in d)ledgerForm();else if('quickLedger'in d)ledgerForm(null,d.quickLedger);else if('editLedger'in d)ledgerForm(d.editLedger);else if('template'in d)createNote(d.template);else if('note'in d){selectedNote=d.note;render()}else if('date'in d){selectedDate=d.date;render()}else if('newEvent'in d)eventForm();else if('eventTemplate'in d)eventForm(null,d.eventTemplate);else if('event'in d)eventForm(d.event)});
$('#toggle-mode').onclick=()=>{mode=mode==='own'?'demo':'own';selectedNote=null;query='';view='all';filter='all';if(mode==='demo')seed();render();toast(mode==='demo'?'正在体验示例，自己的记录不受影响':'已回到自己的记录')};
$('#reset').onclick=()=>{showModal(`<div class="dialog-top"><h2>重置当前原型？</h2><button data-close aria-label="关闭">✕</button></div><p class="subtitle">清空「${names[app][0]}」的${mode==='demo'?'示例':'个人'}空间。其他应用和空间保持不变。</p><div class="dialog-actions"><button id="reset-cancel">取消</button><button class="primary" id="reset-confirm">确认重置</button></div>`);$('#reset-cancel').onclick=()=>$('#modal').close();$('#reset-confirm').onclick=()=>{write([]);if(mode==='demo')seed();selectedNote=null;view='all';query='';filter='all';$('#modal').close();render();toast('当前原型已重置')}};
function route(){app=['ledger','notes','calendar'].includes(location.hash.slice(1))?location.hash.slice(1):'ledger';view='all';filter='all';query='';selectedNote=null;if(mode==='demo')seed();render()}
window.addEventListener('hashchange',route);route();
